# -*- coding: utf-8 -*-
"""optimized_edge_unet_oil_spill

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15l1yHtMKFfnM5TZvL6QZql9d5mrVwAMx
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import cv2
import numpy as np
import tensorflow as tf
from tqdm import tqdm

dataset_path = '/content/drive/MyDrive/Oil spill Research /Dataset Cretaion /Lados Dataset'
project_path = '/content/drive/MyDrive/Oil spill Research /Dataset Cretaion /Edge_UNet_binary_segmentation'

SPILL_IDS = {2, 3, 5}   # emulsion, oil, sheen

IMG_SIZE = 224
BATCH_SIZE = 8
INITIAL_LR = 1e-4
FINE_TUNE_LR = 1e-5
EPOCHS_STAGE_1 = 20
EPOCHS_STAGE_2 = 10
AUTOTUNE = tf.data.AUTOTUNE

print("dataset_path:", dataset_path)
print("project_path:", project_path)

"""Step 2 — Create folders"""

os.makedirs(project_path, exist_ok=True)

for folder in ['processed', 'models', 'plots', 'predictions', 'tflite']:
    os.makedirs(os.path.join(project_path, folder), exist_ok=True)

for split in ['train', 'valid', 'test']:
    os.makedirs(os.path.join(project_path, 'processed', split, 'images'), exist_ok=True)
    os.makedirs(os.path.join(project_path, 'processed', split, 'masks'), exist_ok=True)

print("Folders created successfully.")

"""Step 3 — Convert original masks into binary spill masks"""

def convert_split_to_binary(split_name):
    src_path = os.path.join(dataset_path, split_name)
    dst_img_path = os.path.join(project_path, 'processed', split_name, 'images')
    dst_mask_path = os.path.join(project_path, 'processed', split_name, 'masks')

    files = sorted(os.listdir(src_path))
    image_files = [
        f for f in files
        if f.lower().endswith(('.jpg', '.jpeg', '.png')) and '_mask' not in f.lower()
    ]

    total_images = 0
    total_masks = 0

    for img_file in tqdm(image_files, desc=f"Processing {split_name}"):
        base = os.path.splitext(img_file)[0]
        mask_file = base + "_mask.png"

        img_src = os.path.join(src_path, img_file)
        mask_src = os.path.join(src_path, mask_file)

        if not os.path.exists(mask_src):
            continue

        img = cv2.imread(img_src)
        mask = cv2.imread(mask_src, cv2.IMREAD_UNCHANGED)

        if img is None or mask is None:
            continue

        binary_mask = np.isin(mask, list(SPILL_IDS)).astype(np.uint8)

        cv2.imwrite(os.path.join(dst_img_path, img_file), img)
        cv2.imwrite(os.path.join(dst_mask_path, base + ".png"), binary_mask * 255)

        total_images += 1
        total_masks += 1

    print(f"{split_name}: saved {total_images} images and {total_masks} masks")

for split in ['train', 'valid', 'test']:
    convert_split_to_binary(split)

"""Step 4 — Collect image and mask paths"""

def get_image_mask_paths(split_name):
    img_dir = os.path.join(project_path, 'processed', split_name, 'images')
    mask_dir = os.path.join(project_path, 'processed', split_name, 'masks')

    image_files = sorted(os.listdir(img_dir))
    mask_files = sorted(os.listdir(mask_dir))

    image_paths = [os.path.join(img_dir, f) for f in image_files]
    mask_paths = [os.path.join(mask_dir, f) for f in mask_files]

    return image_paths, mask_paths

train_image_paths, train_mask_paths = get_image_mask_paths('train')
valid_image_paths, valid_mask_paths = get_image_mask_paths('valid')
test_image_paths, test_mask_paths = get_image_mask_paths('test')

print("Train:", len(train_image_paths), len(train_mask_paths))
print("Valid:", len(valid_image_paths), len(valid_mask_paths))
print("Test :", len(test_image_paths), len(test_mask_paths))

"""Step 5 — Build the tf.data pipeline"""

def read_image(path):
    image = tf.io.read_file(path)
    image = tf.image.decode_image(image, channels=3, expand_animations=False)
    image.set_shape([None, None, 3])
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
    image = tf.cast(image, tf.float32)
    image = tf.keras.applications.mobilenet_v2.preprocess_input(image)
    return image

def read_mask(path):
    mask = tf.io.read_file(path)
    mask = tf.image.decode_png(mask, channels=1)
    mask = tf.image.resize(mask, (IMG_SIZE, IMG_SIZE), method='nearest')
    mask = tf.cast(mask > 127, tf.float32)
    return mask

def augment_pair(image, mask):
    if tf.random.uniform(()) > 0.5:
        image = tf.image.flip_left_right(image)
        mask = tf.image.flip_left_right(mask)

    if tf.random.uniform(()) > 0.5:
        image = tf.image.flip_up_down(image)
        mask = tf.image.flip_up_down(mask)

    k = tf.random.uniform(shape=[], minval=0, maxval=4, dtype=tf.int32)
    image = tf.image.rot90(image, k)
    mask = tf.image.rot90(mask, k)

    return image, mask

def load_pair(image_path, mask_path):
    image = read_image(image_path)
    mask = read_mask(mask_path)
    return image, mask

def make_dataset(image_paths, mask_paths, training=False):
    ds = tf.data.Dataset.from_tensor_slices((image_paths, mask_paths))
    ds = ds.map(load_pair, num_parallel_calls=AUTOTUNE)

    if training:
        ds = ds.shuffle(min(len(image_paths), 512), reshuffle_each_iteration=True)
        ds = ds.map(augment_pair, num_parallel_calls=AUTOTUNE)

    ds = ds.cache()
    ds = ds.batch(BATCH_SIZE)
    ds = ds.prefetch(AUTOTUNE)
    return ds

train_ds = make_dataset(train_image_paths, train_mask_paths, training=True)
valid_ds = make_dataset(valid_image_paths, valid_mask_paths, training=False)
test_ds  = make_dataset(test_image_paths, test_mask_paths, training=False)

print("Datasets created.")

"""Step 6 — Check one batch"""

import matplotlib.pyplot as plt

x_batch, y_batch = next(iter(train_ds))

print("Image batch shape:", x_batch.shape)
print("Mask batch shape :", y_batch.shape)

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.imshow((x_batch[0].numpy() + 1.0) / 2.0)  # for display only
plt.title("Sample Image")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(y_batch[0].numpy().squeeze(), cmap='gray')
plt.title("Sample Mask")
plt.axis("off")

plt.show()

"""Step 7 — Define loss and metrics"""

def dice_coef(y_true, y_pred, smooth=1e-6):
    y_true = tf.cast(y_true, tf.float32)
    y_pred = tf.cast(y_pred, tf.float32)

    y_true_f = tf.keras.backend.flatten(y_true)
    y_pred_f = tf.keras.backend.flatten(y_pred)

    intersection = tf.reduce_sum(y_true_f * y_pred_f)
    return (2.0 * intersection + smooth) / (
        tf.reduce_sum(y_true_f) + tf.reduce_sum(y_pred_f) + smooth
    )

def dice_loss(y_true, y_pred):
    return 1.0 - dice_coef(y_true, y_pred)

def bce_dice_loss(y_true, y_pred):
    bce = tf.keras.losses.binary_crossentropy(y_true, y_pred)
    return bce + dice_loss(y_true, y_pred)

"""Step 8 — Build the optimized Edge U-Net"""

def sep_conv_block(x, filters, dropout=0.0):
    x = tf.keras.layers.SeparableConv2D(filters, 3, padding='same', use_bias=False)(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.ReLU()(x)

    x = tf.keras.layers.SeparableConv2D(filters, 3, padding='same', use_bias=False)(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.ReLU()(x)

    if dropout > 0:
        x = tf.keras.layers.Dropout(dropout)(x)
    return x

def build_edge_unet(input_shape=(224, 224, 3), alpha=0.75):
    base = tf.keras.applications.MobileNetV2(
        input_shape=input_shape,
        include_top=False,
        weights='imagenet',
        alpha=alpha
    )

    skip_names = [
        'block_1_expand_relu',
        'block_3_expand_relu',
        'block_6_expand_relu',
        'block_13_expand_relu',
        'block_16_project'
    ]

    skip_outputs = [base.get_layer(name).output for name in skip_names]
    encoder = tf.keras.Model(inputs=base.input, outputs=skip_outputs, name='mobilenetv2_encoder')
    encoder.trainable = False

    inputs = tf.keras.Input(shape=input_shape)
    s1, s2, s3, s4, bottleneck = encoder(inputs, training=False)

    x = bottleneck
    x = tf.keras.layers.UpSampling2D((2, 2), interpolation='bilinear')(x)
    x = tf.keras.layers.Concatenate()([x, s4])
    x = sep_conv_block(x, 128, dropout=0.1)

    x = tf.keras.layers.UpSampling2D((2, 2), interpolation='bilinear')(x)
    x = tf.keras.layers.Concatenate()([x, s3])
    x = sep_conv_block(x, 96, dropout=0.1)

    x = tf.keras.layers.UpSampling2D((2, 2), interpolation='bilinear')(x)
    x = tf.keras.layers.Concatenate()([x, s2])
    x = sep_conv_block(x, 64)

    x = tf.keras.layers.UpSampling2D((2, 2), interpolation='bilinear')(x)
    x = tf.keras.layers.Concatenate()([x, s1])
    x = sep_conv_block(x, 32)

    x = tf.keras.layers.UpSampling2D((2, 2), interpolation='bilinear')(x)
    x = sep_conv_block(x, 16)

    outputs = tf.keras.layers.Conv2D(1, 1, activation='sigmoid', padding='same')(x)

    return tf.keras.Model(inputs, outputs, name='Edge_UNet_MobileNetV2')

"""Step 9 — Compile model"""

def compile_model(model, learning_rate):
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
        loss=bce_dice_loss,
        metrics=[
            dice_coef,
            tf.keras.metrics.BinaryIoU(target_class_ids=[1], threshold=0.5, name='iou'),
            tf.keras.metrics.Precision(name='precision'),
            tf.keras.metrics.Recall(name='recall')
        ]
    )

model = build_edge_unet(input_shape=(IMG_SIZE, IMG_SIZE, 3), alpha=0.75)
compile_model(model, INITIAL_LR)
model.summary()

"""Step 10 — Callbacks"""

def build_callbacks(save_path, monitor='val_dice_coef'):
    return [
        tf.keras.callbacks.ModelCheckpoint(
            save_path,
            monitor=monitor,
            mode='max',
            save_best_only=True,
            verbose=1
        ),
        tf.keras.callbacks.EarlyStopping(
            monitor=monitor,
            mode='max',
            patience=5,
            restore_best_weights=True,
            verbose=1
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor='val_loss',
            factor=0.5,
            patience=2,
            verbose=1
        )
    ]

"""Step 11 — Train stage 1

Freeze encoder first.
"""

stage1_path = os.path.join(project_path, 'models', 'edge_unet_stage1_best.keras')

history_stage1 = model.fit(
    train_ds,
    validation_data=valid_ds,
    epochs=EPOCHS_STAGE_1,
    callbacks=build_callbacks(stage1_path)
)

"""Step 13 — Evaluate on test set"""

best_model = tf.keras.models.load_model(
    stage2_path,
    custom_objects={
        'bce_dice_loss': bce_dice_loss,
        'dice_coef': dice_coef
    }
)

results = best_model.evaluate(test_ds, verbose=1)
print("Metric names:", best_model.metrics_names)
print("Test results:", dict(zip(best_model.metrics_names, results)))

"""Step 14 — Visualize predictions"""

def display_predictions(model, dataset, num_samples=3):
    for images, masks in dataset.take(1):
        preds = model.predict(images)
        preds = (preds > 0.5).astype(np.float32)

        plt.figure(figsize=(12, num_samples * 4))
        for i in range(num_samples):
            plt.subplot(num_samples, 3, i*3 + 1)
            plt.imshow((images[i].numpy() + 1.0) / 2.0)
            plt.title("Image")
            plt.axis("off")

            plt.subplot(num_samples, 3, i*3 + 2)
            plt.imshow(masks[i].numpy().squeeze(), cmap='gray')
            plt.title("True Mask")
            plt.axis("off")

            plt.subplot(num_samples, 3, i*3 + 3)
            plt.imshow(preds[i].squeeze(), cmap='gray')
            plt.title("Predicted Mask")
            plt.axis("off")

        plt.tight_layout()
        plt.show()

display_predictions(best_model, test_ds, num_samples=3)

"""Step 15 — Export int8 TFLite model

This supports your edge/UAV objective in the proposal.
"""

def make_representative_data_gen(train_ds):
    def representative_data_gen():
        for images, _ in train_ds.take(100):
            images_np = images.numpy()
            for i in range(images_np.shape[0]):
                yield [images_np[i:i+1].astype(np.float32)]
    return representative_data_gen

def export_tflite_int8(model, train_ds, output_path):
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = make_representative_data_gen(train_ds)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model = converter.convert()

    with open(output_path, 'wb') as f:
        f.write(tflite_model)

    print("Saved:", output_path)

tflite_path = os.path.join(project_path, 'tflite', 'edge_unet_mobilenetv2_int8.tflite')
export_tflite_int8(best_model, train_ds, tflite_path)