# -*- coding: utf-8 -*-
"""unet

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SK8ed40o03rWijlssXY1ZAYfo_HSTaBF
"""

from google.colab import drive
drive.mount('/content/drive')

dataset_path = '/content/drive/MyDrive/Oil spill Research /Dataset Cretaion /Lados Dataset'
print(f"Dataset path: {dataset_path}")

# Define spill and non-spill IDs (from the original script)
SPILL_IDS = {2, 3, 5}   # emulsion, oil, sheen
NON_SPILL_IDS = {1, 4}  # ship, oil-platform conect this

import os

project_path = '/content/drive/MyDrive/Oil spill Research /Dataset Cretaion /U-Net binary segmentation'

os.makedirs(project_path, exist_ok=True)
os.makedirs(os.path.join(project_path, 'processed'), exist_ok=True)
os.makedirs(os.path.join(project_path, 'models'), exist_ok=True)
os.makedirs(os.path.join(project_path, 'plots'), exist_ok=True)
os.makedirs(os.path.join(project_path, 'predictions'), exist_ok=True)

splits = ['train', 'valid', 'test']

for split in splits:
    os.makedirs(os.path.join(project_path, 'processed', split, 'images'), exist_ok=True)
    os.makedirs(os.path.join(project_path, 'processed', split, 'masks'), exist_ok=True)

print("Project path:", project_path)
print("Folders created successfully.")

import cv2
import numpy as np
from tqdm import tqdm

def convert_split_to_binary(split_name):
    src_path = os.path.join(dataset_path, split_name)
    dst_img_path = os.path.join(project_path, 'processed', split_name, 'images')
    dst_mask_path = os.path.join(project_path, 'processed', split_name, 'masks')

    files = sorted(os.listdir(src_path))

    image_files = [
        f for f in files
        if f.lower().endswith(('.jpg', '.jpeg', '.png')) and '_mask' not in f.lower()
    ]

    total_images = 0
    total_masks = 0

    for img_file in tqdm(image_files, desc=f"Processing {split_name}"):
        base = os.path.splitext(img_file)[0]
        mask_file = base + "_mask.png"

        img_src = os.path.join(src_path, img_file)
        mask_src = os.path.join(src_path, mask_file)

        if not os.path.exists(mask_src):
            continue

        img = cv2.imread(img_src)
        mask = cv2.imread(mask_src, cv2.IMREAD_UNCHANGED)

        if img is None or mask is None:
            continue

        binary_mask = np.isin(mask, list(SPILL_IDS)).astype(np.uint8)

        cv2.imwrite(os.path.join(dst_img_path, img_file), img)
        cv2.imwrite(os.path.join(dst_mask_path, base + ".png"), binary_mask * 255)

        total_images += 1
        total_masks += 1

    print(f"{split_name}: saved {total_images} images and {total_masks} masks")

for split in splits:
    convert_split_to_binary(split)

"""verify the processed data"""

for split in splits:
    img_dir = os.path.join(project_path, 'processed', split, 'images')
    mask_dir = os.path.join(project_path, 'processed', split, 'masks')

    imgs = sorted(os.listdir(img_dir))
    masks = sorted(os.listdir(mask_dir))

    print(f"\n--- {split.upper()} ---")
    print("Images:", len(imgs))
    print("Masks :", len(masks))
    print("Sample image:", imgs[:3])
    print("Sample mask :", masks[:3])

import matplotlib.pyplot as plt

split = 'train'
img_dir = os.path.join(project_path, 'processed', split, 'images')
mask_dir = os.path.join(project_path, 'processed', split, 'masks')

sample_img = sorted(os.listdir(img_dir))[0]
sample_mask = os.path.splitext(sample_img)[0] + '.png'

img = cv2.imread(os.path.join(img_dir, sample_img))
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

mask = cv2.imread(os.path.join(mask_dir, sample_mask), cv2.IMREAD_GRAYSCALE)

print("Sample image:", sample_img)
print("Sample mask :", sample_mask)
print("Mask unique values:", np.unique(mask))

plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.imshow(img)
plt.title("Image")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(mask, cmap='gray')
plt.title("Binary Mask")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(img)
plt.imshow(mask, cmap='jet', alpha=0.4)
plt.title("Overlay")
plt.axis("off")

plt.show()

"""prepare image and mask paths"""

def get_image_mask_paths(split_name):
    img_dir = os.path.join(project_path, 'processed', split_name, 'images')
    mask_dir = os.path.join(project_path, 'processed', split_name, 'masks')

    image_files = sorted(os.listdir(img_dir))
    mask_files = sorted(os.listdir(mask_dir))

    image_paths = [os.path.join(img_dir, f) for f in image_files]
    mask_paths = [os.path.join(mask_dir, f) for f in mask_files]

    return image_paths, mask_paths

train_image_paths, train_mask_paths = get_image_mask_paths('train')
valid_image_paths, valid_mask_paths = get_image_mask_paths('valid')
test_image_paths, test_mask_paths = get_image_mask_paths('test')

print("Train:", len(train_image_paths), len(train_mask_paths))
print("Valid:", len(valid_image_paths), len(valid_mask_paths))
print("Test :", len(test_image_paths), len(test_mask_paths))

import tensorflow as tf
import numpy as np

IMG_SIZE = 256
BATCH_SIZE =4   # if memory error, change to 4

def read_image(path):
    image = tf.io.read_file(path)
    image = tf.image.decode_image(image, channels=3, expand_animations=False)
    image.set_shape([None, None, 3])
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
    image = tf.cast(image, tf.float32) / 255.0
    return image

def read_mask(path):
    mask = tf.io.read_file(path)
    mask = tf.image.decode_png(mask, channels=1)
    mask = tf.image.resize(mask, (IMG_SIZE, IMG_SIZE), method='nearest')
    mask = tf.cast(mask > 127, tf.float32)   # 0/255 -> 0/1
    return mask

def load_pair(image_path, mask_path):
    image = read_image(image_path)
    mask = read_mask(mask_path)
    return image, mask

def make_dataset(image_paths, mask_paths, training=False):
    ds = tf.data.Dataset.from_tensor_slices((image_paths, mask_paths))
    ds = ds.map(load_pair, num_parallel_calls=tf.data.AUTOTUNE)

    if training:
        ds = ds.shuffle(512)

    ds = ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
    return ds

train_ds = make_dataset(train_image_paths, train_mask_paths, training=True)
valid_ds = make_dataset(valid_image_paths, valid_mask_paths, training=False)
test_ds  = make_dataset(test_image_paths, test_mask_paths, training=False)

print("Datasets created successfully.")

import matplotlib.pyplot as plt

x_batch, y_batch = next(iter(train_ds))

print("Image batch shape:", x_batch.shape)
print("Mask batch shape :", y_batch.shape)
print("Image min/max    :", tf.reduce_min(x_batch).numpy(), tf.reduce_max(x_batch).numpy())
print("Mask unique vals :", np.unique(y_batch[0].numpy()))

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.imshow(x_batch[0].numpy())
plt.title("Sample Image")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(y_batch[0].numpy().squeeze(), cmap='gray')
plt.title("Sample Mask")
plt.axis("off")

plt.show()

for i in range(8):
    print(f"Mask {i} unique values:", np.unique(y_batch[i].numpy()))

def conv_block(x, filters):
    x = tf.keras.layers.Conv2D(filters, 3, padding="same")(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Activation("relu")(x)

    x = tf.keras.layers.Conv2D(filters, 3, padding="same")(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Activation("relu")(x)
    return x

def encoder_block(x, filters):
    s = conv_block(x, filters)
    p = tf.keras.layers.MaxPooling2D((2, 2))(s)
    return s, p

def decoder_block(x, skip, filters):
    x = tf.keras.layers.Conv2DTranspose(filters, 2, strides=2, padding="same")(x)
    x = tf.keras.layers.Concatenate()([x, skip])
    x = conv_block(x, filters)
    return x

def build_unet(input_shape=(256, 256, 3)):
    inputs = tf.keras.Input(shape=input_shape)

    s1, p1 = encoder_block(inputs, 64)
    s2, p2 = encoder_block(p1, 128)
    s3, p3 = encoder_block(p2, 256)
    s4, p4 = encoder_block(p3, 512)

    b1 = conv_block(p4, 1024)

    d1 = decoder_block(b1, s4, 512)
    d2 = decoder_block(d1, s3, 256)
    d3 = decoder_block(d2, s2, 128)
    d4 = decoder_block(d3, s1, 64)

    outputs = tf.keras.layers.Conv2D(1, 1, activation="sigmoid", padding="same")(d4)

    return tf.keras.Model(inputs, outputs, name="U_Net_Binary")

def dice_coef(y_true, y_pred, smooth=1e-6):
    y_true = tf.cast(y_true, tf.float32)
    y_pred = tf.cast(y_pred, tf.float32)

    y_true_f = tf.keras.backend.flatten(y_true)
    y_pred_f = tf.keras.backend.flatten(y_pred)

    intersection = tf.reduce_sum(y_true_f * y_pred_f)
    return (2. * intersection + smooth) / (
        tf.reduce_sum(y_true_f) + tf.reduce_sum(y_pred_f) + smooth
    )

def dice_loss(y_true, y_pred):
    return 1.0 - dice_coef(y_true, y_pred)

def bce_dice_loss(y_true, y_pred):
    bce = tf.keras.losses.binary_crossentropy(y_true, y_pred)
    return bce + dice_loss(y_true, y_pred)

model = build_unet(input_shape=(IMG_SIZE, IMG_SIZE, 3))

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss=bce_dice_loss,
    metrics=[
        "accuracy",
        dice_coef,
        tf.keras.metrics.BinaryIoU(target_class_ids=[1], threshold=0.5, name="iou")
    ]
)

model.summary()

unet_save_path = os.path.join(project_path, 'models', 'unet_binary_best.keras')

callbacks = [
    tf.keras.callbacks.ModelCheckpoint(
        unet_save_path,
        monitor='val_dice_coef',
        mode='max',
        save_best_only=True,
        verbose=1
    ),
    tf.keras.callbacks.EarlyStopping(
        monitor='val_dice_coef',
        mode='max',
        patience=5,
        restore_best_weights=True,
        verbose=1
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=2,
        verbose=1
    )
]

history = model.fit(
    train_ds,
    validation_data=valid_ds,
    epochs=20,
    callbacks=callbacks
)